steps:
  - name: "node:16" # Use the Node.js 16 base image
    entrypoint: "npm" # Set the entrypoint to run npm commands
    args: ["ci"] # Install dependencies using npm ci

  - name: "node:16" # Use the Node.js 16 base image again
    entrypoint: "npm" # Set the entrypoint to run npm commands
    args: ["run", "start"] # Start your application using npm run start

images: ["gcr.io/crm-app-428010/crm"] # Placeholder for the image name

env_variables:
  MONGO_URI: mongodb+srv://yigalipsey1996:ZWx3vunp1lyYmvVd@cluster0.rqqf2m3.mongodb.net/
  JWT_SECRET: secretlamsecretket
  PORT: 8080
